### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by excerebrose**

### CODE REVIEW

**Comment by gaieges** [comment]
Not much in the diff! :P

**Comment by excerebrose** [comment]
@gaieges hence why I was thinking this was weird. Want me to create an empty branch and make all data on the diff?

**Comment by excerebrose** [comment]
@gaieges Unable to provide the diff in a normal manner, deleteing committed files leads to a weird timeline, can you please clone the repo?

**Comment by gaieges** [comment]
Haha sorry, yeah the intent is to add comments in code so that we can quickly iterate on changes.  A blank branch would work. I can try myself as well

**Pull request closed without merging**
